- hosts: webservers
  tasks:
    - name: Install git
      ansible.builtin.apt:
        name: git
        state: latest
        update_cache: yes
      become: yes
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes
      become: yes
    - name: Copy nginx conf
      ansible.builtin.copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
      become: yes
      notify:
        - restart nginx
    - name: Copy index.html
      ansible.builtin.template:
        src: files/index.html.j2
        dest: /usr/share/nginx/html/index.html
      become: yes
    - name: Create user
      ansible.builtin.user:
        name: cow
    - name: Set auth key from file
      ansible.posix.authorized_key:
        user: cow
        state: present
        key: "{{ lookup('file', 'files/id_ed25519.pub') }}"
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded