- hosts: servers
  vars:
    root_dir: /usr/share/nginx/html
    nginx_port: 80
  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes
      become: yes
    - name: Copy nginx conf
      ansible.builtin.template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      become: yes
      notify:
        - restart nginx
    - name: Copy index.html
      ansible.builtin.template:
        src: files/index.html.j2
        dest: "{{root_dir}}/index.html"
      become: yes
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes